[package]
name = "pav_render"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
glam.workspace = true
wgpu.workspace = true
bytemuck.workspace = true
anyhow.workspace = true
log.workspace = true
png.workspace = true
pollster.workspace = true
ab_glyph.workspace = true
epaint_default_fonts.workspace = true

[lints]
workspace = true
