[package]
name = "pav_audio"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
pav_core.workspace = true
glam.workspace = true
cpal.workspace = true
anyhow.workspace = true
log.workspace = true

# Web Audio in the browser build.
[target.'cfg(target_arch = "wasm32")'.dependencies]
cpal = { workspace = true, features = ["wasm-bindgen"] }

[lints]
workspace = true
